/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.galettedebroons.view;

import fr.galettedebroons.domain.Tournee;
import fr.galettedebroons.main.Main;
import fr.galettedebroons.model.accessBase.RecupTournee;

/**
*
* @author	Julie Guegnaud
* @author	Melissa Poher
* @since	02/04/2013
*/

public class ajoutTournee extends javax.swing.JFrame {

	public ajoutTournee(Main main, NouveauClient nc) {
    	this.nc_ = nc;
    	this.main_ = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitre = new javax.swing.JLabel();
        labelTournee = new javax.swing.JLabel();
        labelErreur = new javax.swing.JLabel();
        valTournee = new javax.swing.JTextField();
        chekboxLundi = new javax.swing.JCheckBox();
        chekboxMardi = new javax.swing.JCheckBox();
        chekboxMercredi = new javax.swing.JCheckBox();
        chekboxJeudi = new javax.swing.JCheckBox();
        chekboxVendredi = new javax.swing.JCheckBox();
        chekboxSamedi = new javax.swing.JCheckBox();
        chekboxDimanche = new javax.swing.JCheckBox();
        boutonEnregistrer = new javax.swing.JButton();
        boutonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Ajout tounée");
        setPreferredSize(new java.awt.Dimension(598, 300));
        setResizable(false);

        labelTitre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitre.setText("Ajouter une tournée");

        labelTournee.setText("Nom de la tournée :");

        labelErreur.setForeground(new java.awt.Color(153, 0, 0));
        labelErreur.setText("");

        chekboxLundi.setText("Lundi");

        chekboxMardi.setText("Mardi");

        chekboxMercredi.setText("Mercredi");

        chekboxJeudi.setText("Jeudi");

        chekboxVendredi.setText("Vendredi");

        chekboxSamedi.setText("Samedi");

        chekboxDimanche.setText("Dimanche");

        boutonEnregistrer.setText("Enregistrer");
        boutonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	boutonEnregistrerActionPerformed(evt);
            }
        });

        boutonAnnuler.setText("Annuler");
        boutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	boutonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(boutonEnregistrer)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonAnnuler))
                                    .addComponent(labelTitre)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(labelTournee)
                                .addGap(18, 18, 18)
                                .addComponent(valTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(chekboxLundi)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chekboxMardi)
                                    .addComponent(chekboxSamedi))
                                .addGap(18, 18, 18)
                                .addComponent(chekboxMercredi)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chekboxJeudi)
                                        .addGap(18, 18, 18)
                                        .addComponent(chekboxVendredi))
                                    .addComponent(chekboxDimanche))))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelErreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitre)
                .addGap(18, 18, 18)
                .addComponent(labelErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTournee)
                    .addComponent(valTournee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekboxLundi)
                    .addComponent(chekboxMardi)
                    .addComponent(chekboxMercredi)
                    .addComponent(chekboxJeudi)
                    .addComponent(chekboxVendredi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekboxSamedi)
                    .addComponent(chekboxDimanche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonEnregistrer)
                    .addComponent(boutonAnnuler))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void boutonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {
    	//Vérification d'erreur
    	RecupTournee rt = new RecupTournee(main_);
    	String messErreur = "";
    	
		if (valTournee.getText().isEmpty())
			messErreur += "un nom de tournée doit être rempli";
		else if (rt.tourneePresente(valTournee.getText())){
			messErreur += "ce nom de tournée est déjà utilisé";
		}
		
		boolean check = false;
		if(chekboxLundi.isSelected() || chekboxMardi.isSelected() || chekboxMercredi.isSelected() || 
				chekboxJeudi.isSelected() || chekboxVendredi.isSelected() || 
				chekboxSamedi.isSelected() || chekboxDimanche.isSelected())
			check =  true;
		
		if (!check){
			if (messErreur == "")
				messErreur += "il faut sélectionner au moins une checkbox";
			else
				messErreur += "\n et il faut sélectionner au moins une checkbox";
		}
    	
    	if (messErreur == ""){
			main_.getTransaction().begin();
			
			nvGamme_ = new Tournee(valTournee.getText(), 
					chekboxLundi.isSelected(), 
					chekboxMardi.isSelected(), 
					chekboxMercredi.isSelected(), 
					chekboxJeudi.isSelected(), 
					chekboxVendredi.isSelected(), 
					chekboxSamedi.isSelected(), 
					chekboxDimanche.isSelected());
			
			main_.getManager().persist(nvGamme_);
			main_.getTransaction().commit();
			
			this.setVisible(false);
			nc_.MAJComboG();
			nc_.fermetureTournee();
			
    	}
    	else
    		labelErreur.setText("Erreur : " + messErreur);
    }
    
    private void boutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {
    	valTournee.setText("");
    	chekboxLundi.setSelected(false);
    	chekboxMardi.setSelected(false);
    	chekboxMercredi.setSelected(false);
    	chekboxJeudi.setSelected(false);
    	chekboxVendredi.setSelected(false);
    	chekboxSamedi.setSelected(false);
    	chekboxDimanche.setSelected(false);
    	
    	this.setVisible(false);
    }

    private NouveauClient nc_;
	private Main main_;
	private Tournee nvGamme_;
    // Variables declaration - do not modify                     
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonEnregistrer;
    private javax.swing.JCheckBox chekboxDimanche;
    private javax.swing.JCheckBox chekboxJeudi;
    private javax.swing.JCheckBox chekboxLundi;
    private javax.swing.JCheckBox chekboxMardi;
    private javax.swing.JCheckBox chekboxMercredi;
    private javax.swing.JCheckBox chekboxSamedi;
    private javax.swing.JCheckBox chekboxVendredi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelErreur;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JLabel labelTournee;
    private javax.swing.JTextField valTournee;
    // End of variables declaration                   
}
