package fr.galettedebroons.view;

import fr.galettedebroons.controller.LectureFichier;

/**
*
* @author Oumoul
*/
public class AjoutPForm extends javax.swing.JFrame {

	private static final long serialVersionUID = 7360078324094620060L;
	
	private String code_produit;
	private String nature_produit;
	private String nomProduit;
	private String presentation_produit;
	private int qte_lot;
	private String produit_gamme;
	
	/**
    * Creates new form ajoutPForm
    */
   public AjoutPForm(String code_produit) {
       initComponents(code_produit);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents(String code_produit) {

       jLabel1 = new javax.swing.JLabel();
       jLabel_CodeProduit = new javax.swing.JLabel();
       jLabel_NatureProduit = new javax.swing.JLabel();
       jLabel_NomProduit = new javax.swing.JLabel();
       jLabel_PresentationProduit = new javax.swing.JLabel();
       jLabel_QteProduit = new javax.swing.JLabel();
       jLabel_ProduitGamme = new javax.swing.JLabel();
       
       codeprod = new javax.swing.JTextField();
       natureprod = new javax.swing.JTextField();
       
       typprod = new javax.swing.JTextField();
       durprod = new javax.swing.JTextField();
       save = new javax.swing.JButton();
       drop = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setText("AJOUT PRODUIT");

       jLabel_CodeProduit.setText("Code Produit");
       
       jLabel_NatureProduit.setText("Nom Produit");

       jLabel_NomProduit.setText("Type Produit");
       
       jLabel_PresentationProduit.setText("Présentation produit");
       
       jLabel_QteProduit.setText("Quantité produit");

       jLabel_ProduitGamme.setText("Gamme du produit");

       save.setText("Enregistrer");
       save.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               savecliActionPerformed(evt);
           }
       });

       drop.setText("Annuler");
       
       codeprod.setText(code_produit);

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(170, 170, 170)
               .addComponent(jLabel1)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(layout.createSequentialGroup()
               .addGap(37, 37, 37)
               .addComponent(save)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
               .addComponent(drop)
               .addGap(77, 77, 77))
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel_CodeProduit)
                   .addComponent(jLabel_NatureProduit)
                   .addComponent(jLabel_NomProduit)
                   .addComponent(jLabel_PresentationProduit)
                   .addComponent(jLabel_QteProduit)
                   .addComponent(jLabel_ProduitGamme))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addComponent(durprod, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                       .addComponent(typprod, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                       .addComponent(codeprod)))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1)
               .addGap(26, 26, 26)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel_CodeProduit)
                   .addComponent(codeprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(30, 30, 30)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel_NatureProduit)
                   .addComponent(typprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(30, 30, 30)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel_NomProduit)
                   .addComponent(typprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(30, 30, 30)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel_PresentationProduit)
                   .addComponent(typprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(30, 30, 30)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel_QteProduit)
                   .addComponent(typprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(30, 30, 30)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel_ProduitGamme)
                   .addComponent(durprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(46, 46, 46)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(save)
                   .addComponent(drop))
               .addContainerGap(60, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>//GEN-END:initComponents

   private void savecliActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   // pop up pour informer que le client ne sera pas ajouter
	   this.nomProduit = codeprod.getText();
	   this.nature_produit = typprod.getText();
	   this.produit_gamme = durprod.getText();
	   //LectureFichier.createClient(nomProduit, nature_produit, produit_gamme);
	   
   }
   
   
   /**
    * @param args the command line arguments
    */
  

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton drop;
   private javax.swing.JTextField durprod;
   
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel_CodeProduit;
   private javax.swing.JLabel jLabel_NatureProduit;
   private javax.swing.JLabel jLabel_NomProduit;
   private javax.swing.JLabel jLabel_PresentationProduit;
   private javax.swing.JLabel jLabel_QteProduit;
   private javax.swing.JLabel jLabel_ProduitGamme;
   
   private javax.swing.JTextField codeprod;
   private javax.swing.JTextField natureprod;
   private javax.swing.JButton save;
   private javax.swing.JTextField typprod;
   // End of variables declaration//GEN-END:variables
}