package fr.galettedebroons.view;

/**
*
* @author Oumoul
*/
public class AjoutClientForm extends javax.swing.JFrame {

	private static final long serialVersionUID = -772408061681528266L;
	
	/**
    * Creates new form ajoutClientForm
    */
   public AjoutClientForm() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       nmcli = new javax.swing.JTextField();
       adrcli = new javax.swing.JTextField();
       add = new javax.swing.JButton();
       del = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setText("AJOUT CLIENT");

       jLabel3.setText("Nom Client");

       jLabel4.setText("Adresse Client");

       adrcli.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               adrcliActionPerformed(evt);
           }
       });

       add.setText("Ajouter");

       del.setText("Annuler");
       del.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               delcliActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(158, 158, 158)
                       .addComponent(jLabel1))
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel3)
                           .addComponent(jLabel4))
                       .addGap(62, 62, 62)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(adrcli, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                           .addComponent(nmcli))))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(layout.createSequentialGroup()
               .addGap(51, 51, 51)
               .addComponent(add)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
               .addComponent(del)
               .addGap(68, 68, 68))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jLabel1)
               .addGap(42, 42, 42)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel3)
                   .addComponent(nmcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(52, 52, 52)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel4)
                   .addComponent(adrcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(44, 44, 44)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(add)
                   .addComponent(del))
               .addGap(0, 85, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>//GEN-END:initComponents

   private void adrcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrcliActionPerformed
       // TODO add your handling code here:
   }//GEN-LAST:event_adrcliActionPerformed
   
   
   private void delcliActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
	   // pop up pour informer que le client ne sera pas ajouter
	   
	   // Si confirmer alors on ferme
	   this.setVisible(false);
   }

   /**
    * @param args the command line arguments
    */
  

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton add;
   private javax.swing.JTextField adrcli;
   private javax.swing.JButton del;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JTextField nmcli;
   // End of variables declaration//GEN-END:variables
}