package fr.galettedebroons.view;

import java.io.IOException;
import javax.swing.JFileChooser;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

import fr.galettedebroons.controller.LectureFichier;

/**
 *
 * @author	Oumoul Sy
 * @author	Julie Guegnaud
 * @since	16/03/2015
 */
public class FormulaireAjoutDonnees extends javax.swing.JPanel {

    /**
     * Creates new form FormulaireAjoutDonnees
     */
    public FormulaireAjoutDonnees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Titre = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        valFichier = new javax.swing.JTextField();
        boutonParcourir = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        bonLivraison = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        valBonLivraison = new javax.swing.JTextField();
        codeClient = new javax.swing.JLabel();
        valCodeClient = new javax.swing.JComboBox();
        codeArticle = new javax.swing.JLabel();
        valCodeArticle = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        bouttonEnregistrer = new javax.swing.JButton();
        bouttonAnnuler = new javax.swing.JButton();
        valDate = new com.toedter.calendar.JDateChooser();

        Titre.setText("Ajouter les dernières livraisons");
        Titre.setAlignmentY(0.0F);

        labelInfo.setText("Rentrer les informations ou renseigner un fichier");

        valFichier.setText("Fichier.xsl, .ods, .txt, .csv");

        boutonParcourir.setText("Parcourir");
        boutonParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFileChooser choix = new JFileChooser();
                int retour=choix.showOpenDialog(getParent());
                 if(retour==JFileChooser.APPROVE_OPTION){
                	 System.out.println ("un fichier a été choisi (sortie par OK)");
                	 // nom du fichier  choisi 
                	 System.out.println( choix.getSelectedFile().getName());
                	 // chemin absolu du fichier choisi
                	 valFichier. setText(choix.getSelectedFile().getAbsolutePath());
                	 System.out.println(choix.getSelectedFile().getAbsolutePath());
             		}
                // pas de fichier choisi
                else System.out.println("Aucun fichier choisi") ;   
            }
        });

        bonLivraison.setText("Bon de livraison");

        labelDate.setText("Date de livraison");

        codeClient.setText("Code client");

        valCodeClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        codeArticle.setText("Code article");

        valCodeArticle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bouttonEnregistrer.setText("Enregistrer");
        bouttonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	LectureFichier lfe = new LectureFichier();
            	try {
            		lfe.ouverture_fichier(valFichier.getText());
            	} catch (IOException e) {
            		e.printStackTrace();
            	} catch (InvalidFormatException e) {
            		e.printStackTrace();
            	}
            }
        });

        bouttonAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(valFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonParcourir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(Titre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDate)
                                    .addComponent(codeClient)
                                    .addComponent(codeArticle)
                                    .addComponent(bonLivraison))
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(valBonLivraison)
                                        .addComponent(valCodeClient, 0, 87, Short.MAX_VALUE)
                                        .addComponent(valCodeArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(valDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(bouttonEnregistrer)
                .addGap(40, 40, 40)
                .addComponent(bouttonAnnuler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titre)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInfo)
                    .addComponent(valFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonParcourir))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bonLivraison))
                    .addComponent(valBonLivraison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeClient)
                    .addComponent(valCodeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeArticle)
                    .addComponent(valCodeArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouttonEnregistrer)
                    .addComponent(bouttonAnnuler))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Titre;
    private javax.swing.JLabel bonLivraison;
    private javax.swing.JToggleButton boutonParcourir;
    private javax.swing.JLabel codeArticle;
    private javax.swing.JLabel codeClient;
    private javax.swing.JButton bouttonEnregistrer;
    private javax.swing.JButton bouttonAnnuler;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JTextField valBonLivraison;
    private javax.swing.JComboBox valCodeArticle;
    private javax.swing.JComboBox valCodeClient;
    private com.toedter.calendar.JDateChooser valDate;
    private javax.swing.JTextField valFichier;
    // End of variables declaration                   
}
