/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.galettedebroons.view;

import fr.galettedebroons.main.Main;

/**
 *
 * @author Julie
 */
public class InterfaceGenerale extends javax.swing.JFrame {
	
	private static final long serialVersionUID = -1629005008481638796L;
	
    public InterfaceGenerale(Main main) {
        main_ = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                       
    private void initComponents() {

        panelSociete = new javax.swing.JPanel();
        boutonSocieteBroons = new javax.swing.JButton();
        panelOnglet = new javax.swing.JTabbedPane();
        panelCredit = new fr.galettedebroons.view.PanelCredit();
        panelPrevision = new fr.galettedebroons.view.PanelPrevision(main_);
        panelEdition = new fr.galettedebroons.view.PanelEdition(main_, panelPrevision);
        panelParametrage = new fr.galettedebroons.view.MargeModification(main_);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boutonSocieteBroons.setText("Broons");

        javax.swing.GroupLayout panelSocieteLayout = new javax.swing.GroupLayout(panelSociete);
        panelSociete.setLayout(panelSocieteLayout);
        panelSocieteLayout.setHorizontalGroup(
            panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocieteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(boutonSocieteBroons)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSocieteLayout.setVerticalGroup(
            panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSocieteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonSocieteBroons)
                .addContainerGap())
        );
                
        panelOnglet.addTab("Edition", panelEdition);

        panelOnglet.addTab("Prévision semaine", panelPrevision);

        panelOnglet.addTab("Parametrage", panelParametrage);

        panelOnglet.addTab("Crédit", panelCredit);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSociete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelOnglet)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelOnglet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private Main main_;
    // Variables declaration - do not modify                     
    private javax.swing.JButton boutonSocieteBroons;
    private fr.galettedebroons.view.PanelCredit panelCredit;
    private fr.galettedebroons.view.PanelEdition panelEdition;
    private javax.swing.JTabbedPane panelOnglet;
    private fr.galettedebroons.view.PanelPrevision panelPrevision;
    private javax.swing.JPanel panelParametrage;
    private javax.swing.JPanel panelSociete;
    // End of variables declaration                   
}
