package fr.galettedebroons.view;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import fr.galettedebroons.main.Main;
import fr.galettedebroons.model.accessBase.RecupPrevision;

/**
*
* @author poher
*/
public class QteALivrerTotal extends javax.swing.JPanel {
	
	
	/*
	 * To change this template, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/*
	 * QteALivrer.java
	 *
	 * Created on 2 avr. 2015, 11:02:14
	 */
	private Main main_;

	    /** Creates new form QteALivrer */
	    public QteALivrerTotal(Main main) {
	    	this.main_ = main;
	    	rp_ = new RecupPrevision(main_);
	        initComponents();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jDateChooser1 = new com.toedter.calendar.JDateChooser();
	        jDateChooser2 = new com.toedter.calendar.JDateChooser();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jButton1 = new javax.swing.JButton();
	        jLabel4 = new javax.swing.JLabel();
	        
	        jButton1.setText("Voir");
	        jButton1.addActionListener(new java.awt.event.ActionListener(){
	        	public void actionPerformed(java.awt.event.ActionEvent evt) {
	        		jButton1ActionPerformed(evt);
				}
	        });

	        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

	        jLabel1.setText("Quantité totale à livrer par produit");

	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null},
	                {null, null}
	            },
	            new String [] {
	                "Produit", "Total"
	            }
	        ));
	        jScrollPane1.setViewportView(jTable1);

	        jLabel2.setText("Date début");

	        jLabel3.setText("Date fin");
	        
	        jLabel4.setText("Total : ");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel1)
	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
	                            .addComponent(jLabel2)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                            .addComponent(jLabel3)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                            .addComponent(jButton1))
	                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(93, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addContainerGap(261, Short.MAX_VALUE)
	                .addComponent(jLabel4)
	                .addGap(177, 177, 177))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(17, 17, 17)
	                .addComponent(jLabel1)
	                .addGap(38, 38, 38)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel2)
	                    .addComponent(jButton1)
	                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel3)
	                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(11, 11, 11)
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jLabel4)
	                .addContainerGap(41, Short.MAX_VALUE))
	        );
	    }// </editor-fold>
	    
	    private void jButton1ActionPerformed(ActionEvent evt) {
	    	jLabel4.setText("Total : ");
	    	java.util.Date dateDebut = null;
	    	dateDebut = jDateChooser1.getDate();
	    	java.util.Date dateFin = null;
	    	dateFin = jDateChooser2.getDate();
	    	
	    	String monProduit = "";
    		int maQuantite = 0;
    		int maQuantiteTotale = 0;
    		List<Object[]> malisteAAffichee = new ArrayList<Object[]>();
    		
    		ConcurrentHashMap<String, Integer> mapAAffichee = new ConcurrentHashMap();
    		
	    	System.out.println("ma date de début : " +dateDebut);
	    	System.out.println("ma date de fin : " +dateFin);
	    	List<Object[]> maliste = rp_.recupSommeProduit(dateDebut, dateFin);
	    	
	    	// parcours de ma liste de produit - quantité
	    	for (Object[] p : maliste){
    			System.out.println("Mon produit " +p[1]);
    			monProduit = (String) p[1];
    			System.out.println("Ma quantité " +p[0]);
    			maQuantite = (int) p[0];
    			maQuantiteTotale += maQuantite;
    			
    			// tant que j'ai un produit dans ma map a afficher je parcours 
    			// pour voir si le produit n'existe pas déjà
    			Iterator<Map.Entry<String, Integer>> it = mapAAffichee.entrySet().iterator();

    			// si ma liste est vide j'ajoute mon 1er produit
    			if(mapAAffichee.isEmpty()){
        			mapAAffichee.put(monProduit, maQuantite);
        		}
    				
    			else if(mapAAffichee.containsKey(monProduit)){
    				int valeur = mapAAffichee.get(monProduit);
	    			valeur += maQuantite;
	    			    	
	    			mapAAffichee.put(monProduit, valeur);
    			}else{
	    			mapAAffichee.put(monProduit, maQuantite);
	    		}
    		}
	    	
	    	// fin somme dans hashmap -----------
			
	    	// Affichage dans notre JTable1
	    	jTable1.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Produit");
	    	jTable1.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Somme");
	    	
	    	int ligneProduit = 0;
			int colonneProduit = 0;
			int ligneQuantité = 0;
			int colonneQuantité = 1;
	    	
	    	Iterator<Map.Entry<String, Integer>> it2 = mapAAffichee.entrySet().iterator();
			while(it2.hasNext()) {
				
				
				Map.Entry entry = (Map.Entry) it2.next();
				String cle = (String) entry.getKey();
 			    Integer valeur = (Integer) entry.getValue();
				System.out.println("MA clé : " +cle +"et ma valeur : " +valeur);
				jTable1.getModel().setValueAt(cle, ligneProduit, colonneProduit);
				ligneProduit++;
				jTable1.getModel().setValueAt(valeur, ligneQuantité, colonneQuantité);
				ligneQuantité++;
			}
			
			jLabel4.setText(jLabel4.getText() + " " +maQuantiteTotale);
			
			
			
	    }

	    private RecupPrevision rp_;
	    // Variables declaration - do not modify
	    private javax.swing.JButton jButton1;
	    private com.toedter.calendar.JDateChooser jDateChooser1;
	    private com.toedter.calendar.JDateChooser jDateChooser2;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTable jTable1;
	    // End of variables declaration

}
